### ISSUE TITLE
Auth not found

### ISSUE THREAD

**Issue by Thegreekman76** [jason810496/FastAPI-Vue-OAuth2#2]
Hello, first, thank you very much for the development, I wanted to tell you that I am using the backend and the frontend separately, everything is working (that is, running client and server) when I log in it stays in an endless loop where the frontend wants to refresh the token. When I see the uviron log it shows me this:
127.0.0.1:62349 - "POST /api/auth/login HTTP/1.1" 200 OK
INFO: 127.0.0.1:62349 - "GET /api/users/me HTTP/1.1" 401 Unauthorized
Although the login is ok, when it brings up the logged in user it tells me that it is not authorized. I try from Swagger to do it manually and I get exactly the same thing, the login is ok but if I execute the user/me it gives me 401 indicating that it is not authorized. for what is this. thank you so much.

![image](https://github.com/jason810496/FastAPI-Vue-OAuth2/assets/63590318/81e538fa-bf65-4ef2-a492-4b8319e8ef51)

**Comment by jason810496** [comment]
Could you describe the case that caused the issue? 
For example, it might be that only the access token is expired while the refresh token remains valid.

I encountered a similar situation during development. I thought I had already resolved the problems. 😓
 By the way, I found a typo that might be causing the issue (already pushed to the main branch). 
 You could pull the latest version to check whether it works well!

**Comment by Thegreekman76** [comment]
INFO:     127.0.0.1:60594 - "POST /api/auth/refresh HTTP/1.1" 200 OK
INFO:     127.0.0.1:60595 - "GET /api/users/me HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:60594 - "POST /api/auth/refresh HTTP/1.1" 200 OK
INFO:     127.0.0.1:60595 - "GET /api/users/me HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:60594 - "POST /api/auth/refresh HTTP/1.1" 200 OK

It still has the same error after pulling the code, I think the error is in the backend, since it logs in but when it wants to show the current user it says that it does not have authorization. thanks and helppppp ;-)

**Comment by jason810496** [comment]
If you use only the backend to test the refresh utility, will you still receive a 401 error response, or does it work well?

I believe the issue still lies within the frontend. Could you document the error situation of the endless loop? That would be very helpful for me to figure out the bugs👍

**Comment by Thegreekman76** [comment]
> Si usa solo el backend para probar la utilidad de actualización, ¿seguirá recibiendo una respuesta de error 401 o funciona bien?
> 
> Creo que el problema aún se encuentra dentro de la vanguardia. ¿Podría documentar la situación de error del bucle sin fin? Eso sería muy útil para mí para descubrir los errores👍

I log in from the backend and it works ok. If I use the refresh_token generated from the login to execute it within /api/auth/refresh it works ok, that is, it generates the token again, but if I run /api/users/ it tells me that is not authorized

**Comment by Thegreekman76** [comment]
![image](https://github.com/jason810496/FastAPI-Vue-OAuth2/assets/63590318/83878463-2685-456a-829a-daa6cba8b4ea)

**Comment by jason810496** [comment]
I have committed a refactored version.
Please note that if you are using Docker or Docker Compose 🐬, you should delete the containers and images from the previous version, build a new image, and start the container using the latest code.

I hope the current version solves the problems!

**Comment by Thegreekman76** [comment]
Sorry, it's still doing the same loop after logging in. The loop switches between refreshing the token and displaying the user's data.

backend 
![image](https://github.com/jason810496/FastAPI-Vue-OAuth2/assets/63590318/44f7ae8d-020b-413c-a620-29afb6a9bea4)

frontend
![image](https://github.com/jason810496/FastAPI-Vue-OAuth2/assets/63590318/83e1fb32-eabd-4692-b848-27928665fb0b)
![image](https://github.com/jason810496/FastAPI-Vue-OAuth2/assets/63590318/86f93d9f-dd8c-493a-b53a-83ea2577e490)

**Comment by jason810496** [comment]
How about we meet online and figure out the bugs?
Could you please present the issues on your computer since I can't replicate the problem on my PC?
What do you think? 💫
