### ISSUE TITLE
Updating access token on request

### ISSUE THREAD

**Issue by DIMFLIX-OFFICIAL** [jason810496/FastAPI-Vue-OAuth2#3]
Hi, I'd like to ask you a question:
On the client side, access_token and refresh_token are stored in store Vue during authorisation.

Suppose access_token expired and I was on the site all this time. And let's say I want to send api request to private method (authorisation is needed). 

So here is the question: do I need to update the access_token before the request? Because if I don't do it, the request will be sent with invalid token and we will get an error that the user is not authorised, although he just needs to update the access_token.

Or have I somehow missed the point where you have implemented such a thing? Please tell me.

**Comment by DIMFLIX-OFFICIAL** [comment]
But it expires. I understand on the client side that we need to constantly check the expiration date access token. And if it has expired, then update it.

The question is implementation, how best to do it?

1 - You can make a constant cycle of checking the token, and update it if the time expires.

2 - Configure axios so that a certain function must be executed before the request. This function will check the token, and if it has expired, it will update it, and then make the request that I gave.

Which option would be better? Maybe you can recommend something?

I just liked your system and I want to implement it on my website. And I need the user to have a constantly updated token in order to make requests to the API. There won't be a refresh button. Therefore, you need to figure out how the access token will be updated automatically.

**Comment by jason810496** [comment]
The second solution is more appropriate.

The workflow of the current project is as follows:

- Use `axios` to make protected API requests with the `access_token`.
   - If the response code is `401`:
     - Use the `refresh_token` to retrieve a new `access_token`.
       - If the response code is `401`:
         - Reset the `access_token` and `refresh_token` in the store and redirect the user to the login page.
       - If the response code is `200`:
         - Set the new `access_token` and `refresh_token` in the store and redirect the user to the protected page.

I use `axios interceptors` to implement the above solution.
Check out [/frontend/src/api/req.js](https://github.com/jason810496/FastAPI-Vue-OAuth2/blob/1f3f170e5f562027b29f01c40b4f4b1e42468d5c/frontend/src/api/req.js#L10C1-L10C1) for more details 👀.

**Comment by jason810496** [comment]
By the way, the current version of this project (on the `main` branch) doesn't implement the best practices of OAuth2. 😓

There are several improvements:
- The `access_token` should only be stored in memory (not in `localStorage`).
- The `refresh_token` should be stored in `HttpOnly` cookies (not normal cookies).
- `Pinia` is recommended for Vue3 projects, not `VueX`.

I'm currently working on implementing the best practices mentioned above on the `development` branch.
I plan to update the changes to the `main` branch in the coming days.

**Comment by DIMFLIX-OFFICIAL** [comment]
Ok, thank you
